// Code generated by Prisma (prisma@1.25.6). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { DocumentNode } from "graphql";
import {
  makePrismaClientClass,
  BaseClientOptions,
  Model
} from "prisma-client-lib";
import { typeDefs } from "./prisma-schema";

export type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];

export interface Exists {
  food: (where?: FoodWhereInput) => Promise<boolean>;
  space: (where?: SpaceWhereInput) => Promise<boolean>;
}

export interface Node {}

export type FragmentableArray<T> = Promise<Array<T>> & Fragmentable;

export interface Fragmentable {
  $fragment<T>(fragment: string | DocumentNode): Promise<T>;
}

export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;

  /**
   * Queries
   */

  food: (where: FoodWhereUniqueInput) => FoodPromise;
  foods: (args?: {
    where?: FoodWhereInput;
    orderBy?: FoodOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<Food>;
  foodsConnection: (args?: {
    where?: FoodWhereInput;
    orderBy?: FoodOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FoodConnectionPromise;
  space: (where: SpaceWhereUniqueInput) => SpacePromise;
  spaces: (args?: {
    where?: SpaceWhereInput;
    orderBy?: SpaceOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<Space>;
  spacesConnection: (args?: {
    where?: SpaceWhereInput;
    orderBy?: SpaceOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => SpaceConnectionPromise;
  node: (args: { id: ID_Output }) => Node;

  /**
   * Mutations
   */

  createFood: (data: FoodCreateInput) => FoodPromise;
  updateFood: (args: {
    data: FoodUpdateInput;
    where: FoodWhereUniqueInput;
  }) => FoodPromise;
  updateManyFoods: (args: {
    data: FoodUpdateManyMutationInput;
    where?: FoodWhereInput;
  }) => BatchPayloadPromise;
  upsertFood: (args: {
    where: FoodWhereUniqueInput;
    create: FoodCreateInput;
    update: FoodUpdateInput;
  }) => FoodPromise;
  deleteFood: (where: FoodWhereUniqueInput) => FoodPromise;
  deleteManyFoods: (where?: FoodWhereInput) => BatchPayloadPromise;
  createSpace: (data: SpaceCreateInput) => SpacePromise;
  updateSpace: (args: {
    data: SpaceUpdateInput;
    where: SpaceWhereUniqueInput;
  }) => SpacePromise;
  updateManySpaces: (args: {
    data: SpaceUpdateManyMutationInput;
    where?: SpaceWhereInput;
  }) => BatchPayloadPromise;
  upsertSpace: (args: {
    where: SpaceWhereUniqueInput;
    create: SpaceCreateInput;
    update: SpaceUpdateInput;
  }) => SpacePromise;
  deleteSpace: (where: SpaceWhereUniqueInput) => SpacePromise;
  deleteManySpaces: (where?: SpaceWhereInput) => BatchPayloadPromise;

  /**
   * Subscriptions
   */

  $subscribe: Subscription;
}

export interface Subscription {
  food: (
    where?: FoodSubscriptionWhereInput
  ) => FoodSubscriptionPayloadSubscription;
  space: (
    where?: SpaceSubscriptionWhereInput
  ) => SpaceSubscriptionPayloadSubscription;
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T;
}

/**
 * Types
 */

export type FoodOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "name_ASC"
  | "name_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type StorageMethod = "FROZEN" | "COLD" | "NATURAL";

export type SpaceOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "name_ASC"
  | "name_DESC"
  | "storeAs_ASC"
  | "storeAs_DESC"
  | "icon_ASC"
  | "icon_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type MutationType = "CREATED" | "UPDATED" | "DELETED";

export type FoodWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export interface FoodWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  AND?: FoodWhereInput[] | FoodWhereInput;
  OR?: FoodWhereInput[] | FoodWhereInput;
  NOT?: FoodWhereInput[] | FoodWhereInput;
}

export type SpaceWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export interface SpaceWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  storeAs?: StorageMethod;
  storeAs_not?: StorageMethod;
  storeAs_in?: StorageMethod[] | StorageMethod;
  storeAs_not_in?: StorageMethod[] | StorageMethod;
  foods_every?: FoodWhereInput;
  foods_some?: FoodWhereInput;
  foods_none?: FoodWhereInput;
  icon?: String;
  icon_not?: String;
  icon_in?: String[] | String;
  icon_not_in?: String[] | String;
  icon_lt?: String;
  icon_lte?: String;
  icon_gt?: String;
  icon_gte?: String;
  icon_contains?: String;
  icon_not_contains?: String;
  icon_starts_with?: String;
  icon_not_starts_with?: String;
  icon_ends_with?: String;
  icon_not_ends_with?: String;
  AND?: SpaceWhereInput[] | SpaceWhereInput;
  OR?: SpaceWhereInput[] | SpaceWhereInput;
  NOT?: SpaceWhereInput[] | SpaceWhereInput;
}

export interface FoodCreateInput {
  name: String;
}

export interface FoodUpdateInput {
  name?: String;
}

export interface FoodUpdateManyMutationInput {
  name?: String;
}

export interface SpaceCreateInput {
  name: String;
  storeAs: StorageMethod;
  foods?: FoodCreateManyInput;
  icon?: String;
}

export interface FoodCreateManyInput {
  create?: FoodCreateInput[] | FoodCreateInput;
  connect?: FoodWhereUniqueInput[] | FoodWhereUniqueInput;
}

export interface SpaceUpdateInput {
  name?: String;
  storeAs?: StorageMethod;
  foods?: FoodUpdateManyInput;
  icon?: String;
}

export interface FoodUpdateManyInput {
  create?: FoodCreateInput[] | FoodCreateInput;
  update?:
    | FoodUpdateWithWhereUniqueNestedInput[]
    | FoodUpdateWithWhereUniqueNestedInput;
  upsert?:
    | FoodUpsertWithWhereUniqueNestedInput[]
    | FoodUpsertWithWhereUniqueNestedInput;
  delete?: FoodWhereUniqueInput[] | FoodWhereUniqueInput;
  connect?: FoodWhereUniqueInput[] | FoodWhereUniqueInput;
  disconnect?: FoodWhereUniqueInput[] | FoodWhereUniqueInput;
  deleteMany?: FoodScalarWhereInput[] | FoodScalarWhereInput;
  updateMany?:
    | FoodUpdateManyWithWhereNestedInput[]
    | FoodUpdateManyWithWhereNestedInput;
}

export interface FoodUpdateWithWhereUniqueNestedInput {
  where: FoodWhereUniqueInput;
  data: FoodUpdateDataInput;
}

export interface FoodUpdateDataInput {
  name?: String;
}

export interface FoodUpsertWithWhereUniqueNestedInput {
  where: FoodWhereUniqueInput;
  update: FoodUpdateDataInput;
  create: FoodCreateInput;
}

export interface FoodScalarWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  AND?: FoodScalarWhereInput[] | FoodScalarWhereInput;
  OR?: FoodScalarWhereInput[] | FoodScalarWhereInput;
  NOT?: FoodScalarWhereInput[] | FoodScalarWhereInput;
}

export interface FoodUpdateManyWithWhereNestedInput {
  where: FoodScalarWhereInput;
  data: FoodUpdateManyDataInput;
}

export interface FoodUpdateManyDataInput {
  name?: String;
}

export interface SpaceUpdateManyMutationInput {
  name?: String;
  storeAs?: StorageMethod;
  icon?: String;
}

export interface FoodSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: FoodWhereInput;
  AND?: FoodSubscriptionWhereInput[] | FoodSubscriptionWhereInput;
  OR?: FoodSubscriptionWhereInput[] | FoodSubscriptionWhereInput;
  NOT?: FoodSubscriptionWhereInput[] | FoodSubscriptionWhereInput;
}

export interface SpaceSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: SpaceWhereInput;
  AND?: SpaceSubscriptionWhereInput[] | SpaceSubscriptionWhereInput;
  OR?: SpaceSubscriptionWhereInput[] | SpaceSubscriptionWhereInput;
  NOT?: SpaceSubscriptionWhereInput[] | SpaceSubscriptionWhereInput;
}

export interface NodeNode {
  id: ID_Output;
}

export interface Food {
  id: ID_Output;
  name: String;
}

export interface FoodPromise extends Promise<Food>, Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
}

export interface FoodSubscription
  extends Promise<AsyncIterator<Food>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface FoodConnection {
  pageInfo: PageInfo;
  edges: FoodEdge[];
}

export interface FoodConnectionPromise
  extends Promise<FoodConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<FoodEdge>>() => T;
  aggregate: <T = AggregateFoodPromise>() => T;
}

export interface FoodConnectionSubscription
  extends Promise<AsyncIterator<FoodConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<FoodEdgeSubscription>>>() => T;
  aggregate: <T = AggregateFoodSubscription>() => T;
}

export interface PageInfo {
  hasNextPage: Boolean;
  hasPreviousPage: Boolean;
  startCursor?: String;
  endCursor?: String;
}

export interface PageInfoPromise extends Promise<PageInfo>, Fragmentable {
  hasNextPage: () => Promise<Boolean>;
  hasPreviousPage: () => Promise<Boolean>;
  startCursor: () => Promise<String>;
  endCursor: () => Promise<String>;
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfo>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>;
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>;
  startCursor: () => Promise<AsyncIterator<String>>;
  endCursor: () => Promise<AsyncIterator<String>>;
}

export interface FoodEdge {
  node: Food;
  cursor: String;
}

export interface FoodEdgePromise extends Promise<FoodEdge>, Fragmentable {
  node: <T = FoodPromise>() => T;
  cursor: () => Promise<String>;
}

export interface FoodEdgeSubscription
  extends Promise<AsyncIterator<FoodEdge>>,
    Fragmentable {
  node: <T = FoodSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateFood {
  count: Int;
}

export interface AggregateFoodPromise
  extends Promise<AggregateFood>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateFoodSubscription
  extends Promise<AsyncIterator<AggregateFood>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface Space {
  id: ID_Output;
  name: String;
  storeAs: StorageMethod;
  icon?: String;
}

export interface SpacePromise extends Promise<Space>, Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  storeAs: () => Promise<StorageMethod>;
  foods: <T = FragmentableArray<Food>>(args?: {
    where?: FoodWhereInput;
    orderBy?: FoodOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => T;
  icon: () => Promise<String>;
}

export interface SpaceSubscription
  extends Promise<AsyncIterator<Space>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  storeAs: () => Promise<AsyncIterator<StorageMethod>>;
  foods: <T = Promise<AsyncIterator<FoodSubscription>>>(args?: {
    where?: FoodWhereInput;
    orderBy?: FoodOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => T;
  icon: () => Promise<AsyncIterator<String>>;
}

export interface SpaceConnection {
  pageInfo: PageInfo;
  edges: SpaceEdge[];
}

export interface SpaceConnectionPromise
  extends Promise<SpaceConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<SpaceEdge>>() => T;
  aggregate: <T = AggregateSpacePromise>() => T;
}

export interface SpaceConnectionSubscription
  extends Promise<AsyncIterator<SpaceConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<SpaceEdgeSubscription>>>() => T;
  aggregate: <T = AggregateSpaceSubscription>() => T;
}

export interface SpaceEdge {
  node: Space;
  cursor: String;
}

export interface SpaceEdgePromise extends Promise<SpaceEdge>, Fragmentable {
  node: <T = SpacePromise>() => T;
  cursor: () => Promise<String>;
}

export interface SpaceEdgeSubscription
  extends Promise<AsyncIterator<SpaceEdge>>,
    Fragmentable {
  node: <T = SpaceSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateSpace {
  count: Int;
}

export interface AggregateSpacePromise
  extends Promise<AggregateSpace>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateSpaceSubscription
  extends Promise<AsyncIterator<AggregateSpace>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface BatchPayload {
  count: Long;
}

export interface BatchPayloadPromise
  extends Promise<BatchPayload>,
    Fragmentable {
  count: () => Promise<Long>;
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayload>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>;
}

export interface FoodSubscriptionPayload {
  mutation: MutationType;
  node: Food;
  updatedFields: String[];
  previousValues: FoodPreviousValues;
}

export interface FoodSubscriptionPayloadPromise
  extends Promise<FoodSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = FoodPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = FoodPreviousValuesPromise>() => T;
}

export interface FoodSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<FoodSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = FoodSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = FoodPreviousValuesSubscription>() => T;
}

export interface FoodPreviousValues {
  id: ID_Output;
  name: String;
}

export interface FoodPreviousValuesPromise
  extends Promise<FoodPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
}

export interface FoodPreviousValuesSubscription
  extends Promise<AsyncIterator<FoodPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface SpaceSubscriptionPayload {
  mutation: MutationType;
  node: Space;
  updatedFields: String[];
  previousValues: SpacePreviousValues;
}

export interface SpaceSubscriptionPayloadPromise
  extends Promise<SpaceSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = SpacePromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = SpacePreviousValuesPromise>() => T;
}

export interface SpaceSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<SpaceSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = SpaceSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = SpacePreviousValuesSubscription>() => T;
}

export interface SpacePreviousValues {
  id: ID_Output;
  name: String;
  storeAs: StorageMethod;
  icon?: String;
}

export interface SpacePreviousValuesPromise
  extends Promise<SpacePreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  storeAs: () => Promise<StorageMethod>;
  icon: () => Promise<String>;
}

export interface SpacePreviousValuesSubscription
  extends Promise<AsyncIterator<SpacePreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  storeAs: () => Promise<AsyncIterator<StorageMethod>>;
  icon: () => Promise<AsyncIterator<String>>;
}

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number;
export type ID_Output = string;

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string;

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number;

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean;

export type Long = string;

/**
 * Model Metadata
 */

export const models: Model[] = [
  {
    name: "Food",
    embedded: false
  },
  {
    name: "Space",
    embedded: false
  },
  {
    name: "StorageMethod",
    embedded: false
  }
];

/**
 * Type Defs
 */

export const prisma: Prisma;
