module.exports = {
        typeDefs: // Code generated by Prisma (prisma@1.34.0). DO NOT EDIT.
  // Please don't change this file manually but run `prisma generate` to update it.
  // For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

/* GraphQL */ `type AggregateFood {
  count: Int!
}

type AggregateIngredient {
  count: Int!
}

type AggregateRecipe {
  count: Int!
}

type AggregateSpace {
  count: Int!
}

type AggregateStoredFood {
  count: Int!
}

type AggregateValidEstimate {
  count: Int!
}

type BatchPayload {
  count: Long!
}

scalar DateTime

type Food {
  id: ID!
  name: String!
  barCode: String
  validEstimates(where: ValidEstimateWhereInput, orderBy: ValidEstimateOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [ValidEstimate!]
  updatedAt: DateTime!
  createdAt: DateTime!
}

type FoodConnection {
  pageInfo: PageInfo!
  edges: [FoodEdge]!
  aggregate: AggregateFood!
}

input FoodCreateInput {
  id: ID
  name: String!
  barCode: String
  validEstimates: ValidEstimateCreateManyInput
}

input FoodCreateOneInput {
  create: FoodCreateInput
  connect: FoodWhereUniqueInput
}

type FoodEdge {
  node: Food!
  cursor: String!
}

enum FoodOrderByInput {
  id_ASC
  id_DESC
  name_ASC
  name_DESC
  barCode_ASC
  barCode_DESC
  updatedAt_ASC
  updatedAt_DESC
  createdAt_ASC
  createdAt_DESC
}

type FoodPreviousValues {
  id: ID!
  name: String!
  barCode: String
  updatedAt: DateTime!
  createdAt: DateTime!
}

type FoodSubscriptionPayload {
  mutation: MutationType!
  node: Food
  updatedFields: [String!]
  previousValues: FoodPreviousValues
}

input FoodSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: FoodWhereInput
  AND: [FoodSubscriptionWhereInput!]
  OR: [FoodSubscriptionWhereInput!]
  NOT: [FoodSubscriptionWhereInput!]
}

input FoodUpdateDataInput {
  name: String
  barCode: String
  validEstimates: ValidEstimateUpdateManyInput
}

input FoodUpdateInput {
  name: String
  barCode: String
  validEstimates: ValidEstimateUpdateManyInput
}

input FoodUpdateManyMutationInput {
  name: String
  barCode: String
}

input FoodUpdateOneRequiredInput {
  create: FoodCreateInput
  update: FoodUpdateDataInput
  upsert: FoodUpsertNestedInput
  connect: FoodWhereUniqueInput
}

input FoodUpsertNestedInput {
  update: FoodUpdateDataInput!
  create: FoodCreateInput!
}

input FoodWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  name: String
  name_not: String
  name_in: [String!]
  name_not_in: [String!]
  name_lt: String
  name_lte: String
  name_gt: String
  name_gte: String
  name_contains: String
  name_not_contains: String
  name_starts_with: String
  name_not_starts_with: String
  name_ends_with: String
  name_not_ends_with: String
  barCode: String
  barCode_not: String
  barCode_in: [String!]
  barCode_not_in: [String!]
  barCode_lt: String
  barCode_lte: String
  barCode_gt: String
  barCode_gte: String
  barCode_contains: String
  barCode_not_contains: String
  barCode_starts_with: String
  barCode_not_starts_with: String
  barCode_ends_with: String
  barCode_not_ends_with: String
  validEstimates_every: ValidEstimateWhereInput
  validEstimates_some: ValidEstimateWhereInput
  validEstimates_none: ValidEstimateWhereInput
  updatedAt: DateTime
  updatedAt_not: DateTime
  updatedAt_in: [DateTime!]
  updatedAt_not_in: [DateTime!]
  updatedAt_lt: DateTime
  updatedAt_lte: DateTime
  updatedAt_gt: DateTime
  updatedAt_gte: DateTime
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  AND: [FoodWhereInput!]
  OR: [FoodWhereInput!]
  NOT: [FoodWhereInput!]
}

input FoodWhereUniqueInput {
  id: ID
}

type Ingredient {
  id: ID!
  amount: Int
  measure: Measure!
  food: Food!
}

type IngredientConnection {
  pageInfo: PageInfo!
  edges: [IngredientEdge]!
  aggregate: AggregateIngredient!
}

input IngredientCreateInput {
  id: ID
  amount: Int
  measure: Measure!
  food: FoodCreateOneInput!
}

input IngredientCreateManyInput {
  create: [IngredientCreateInput!]
  connect: [IngredientWhereUniqueInput!]
}

type IngredientEdge {
  node: Ingredient!
  cursor: String!
}

enum IngredientOrderByInput {
  id_ASC
  id_DESC
  amount_ASC
  amount_DESC
  measure_ASC
  measure_DESC
}

type IngredientPreviousValues {
  id: ID!
  amount: Int
  measure: Measure!
}

input IngredientScalarWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  amount: Int
  amount_not: Int
  amount_in: [Int!]
  amount_not_in: [Int!]
  amount_lt: Int
  amount_lte: Int
  amount_gt: Int
  amount_gte: Int
  measure: Measure
  measure_not: Measure
  measure_in: [Measure!]
  measure_not_in: [Measure!]
  AND: [IngredientScalarWhereInput!]
  OR: [IngredientScalarWhereInput!]
  NOT: [IngredientScalarWhereInput!]
}

type IngredientSubscriptionPayload {
  mutation: MutationType!
  node: Ingredient
  updatedFields: [String!]
  previousValues: IngredientPreviousValues
}

input IngredientSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: IngredientWhereInput
  AND: [IngredientSubscriptionWhereInput!]
  OR: [IngredientSubscriptionWhereInput!]
  NOT: [IngredientSubscriptionWhereInput!]
}

input IngredientUpdateDataInput {
  amount: Int
  measure: Measure
  food: FoodUpdateOneRequiredInput
}

input IngredientUpdateInput {
  amount: Int
  measure: Measure
  food: FoodUpdateOneRequiredInput
}

input IngredientUpdateManyDataInput {
  amount: Int
  measure: Measure
}

input IngredientUpdateManyInput {
  create: [IngredientCreateInput!]
  update: [IngredientUpdateWithWhereUniqueNestedInput!]
  upsert: [IngredientUpsertWithWhereUniqueNestedInput!]
  delete: [IngredientWhereUniqueInput!]
  connect: [IngredientWhereUniqueInput!]
  set: [IngredientWhereUniqueInput!]
  disconnect: [IngredientWhereUniqueInput!]
  deleteMany: [IngredientScalarWhereInput!]
  updateMany: [IngredientUpdateManyWithWhereNestedInput!]
}

input IngredientUpdateManyMutationInput {
  amount: Int
  measure: Measure
}

input IngredientUpdateManyWithWhereNestedInput {
  where: IngredientScalarWhereInput!
  data: IngredientUpdateManyDataInput!
}

input IngredientUpdateWithWhereUniqueNestedInput {
  where: IngredientWhereUniqueInput!
  data: IngredientUpdateDataInput!
}

input IngredientUpsertWithWhereUniqueNestedInput {
  where: IngredientWhereUniqueInput!
  update: IngredientUpdateDataInput!
  create: IngredientCreateInput!
}

input IngredientWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  amount: Int
  amount_not: Int
  amount_in: [Int!]
  amount_not_in: [Int!]
  amount_lt: Int
  amount_lte: Int
  amount_gt: Int
  amount_gte: Int
  measure: Measure
  measure_not: Measure
  measure_in: [Measure!]
  measure_not_in: [Measure!]
  food: FoodWhereInput
  AND: [IngredientWhereInput!]
  OR: [IngredientWhereInput!]
  NOT: [IngredientWhereInput!]
}

input IngredientWhereUniqueInput {
  id: ID
}

scalar Long

enum Measure {
  ML
  GRAM
}

type Mutation {
  createFood(data: FoodCreateInput!): Food!
  updateFood(data: FoodUpdateInput!, where: FoodWhereUniqueInput!): Food
  updateManyFoods(data: FoodUpdateManyMutationInput!, where: FoodWhereInput): BatchPayload!
  upsertFood(where: FoodWhereUniqueInput!, create: FoodCreateInput!, update: FoodUpdateInput!): Food!
  deleteFood(where: FoodWhereUniqueInput!): Food
  deleteManyFoods(where: FoodWhereInput): BatchPayload!
  createIngredient(data: IngredientCreateInput!): Ingredient!
  updateIngredient(data: IngredientUpdateInput!, where: IngredientWhereUniqueInput!): Ingredient
  updateManyIngredients(data: IngredientUpdateManyMutationInput!, where: IngredientWhereInput): BatchPayload!
  upsertIngredient(where: IngredientWhereUniqueInput!, create: IngredientCreateInput!, update: IngredientUpdateInput!): Ingredient!
  deleteIngredient(where: IngredientWhereUniqueInput!): Ingredient
  deleteManyIngredients(where: IngredientWhereInput): BatchPayload!
  createRecipe(data: RecipeCreateInput!): Recipe!
  updateRecipe(data: RecipeUpdateInput!, where: RecipeWhereUniqueInput!): Recipe
  updateManyRecipes(data: RecipeUpdateManyMutationInput!, where: RecipeWhereInput): BatchPayload!
  upsertRecipe(where: RecipeWhereUniqueInput!, create: RecipeCreateInput!, update: RecipeUpdateInput!): Recipe!
  deleteRecipe(where: RecipeWhereUniqueInput!): Recipe
  deleteManyRecipes(where: RecipeWhereInput): BatchPayload!
  createSpace(data: SpaceCreateInput!): Space!
  updateSpace(data: SpaceUpdateInput!, where: SpaceWhereUniqueInput!): Space
  updateManySpaces(data: SpaceUpdateManyMutationInput!, where: SpaceWhereInput): BatchPayload!
  upsertSpace(where: SpaceWhereUniqueInput!, create: SpaceCreateInput!, update: SpaceUpdateInput!): Space!
  deleteSpace(where: SpaceWhereUniqueInput!): Space
  deleteManySpaces(where: SpaceWhereInput): BatchPayload!
  createStoredFood(data: StoredFoodCreateInput!): StoredFood!
  updateStoredFood(data: StoredFoodUpdateInput!, where: StoredFoodWhereUniqueInput!): StoredFood
  updateManyStoredFoods(data: StoredFoodUpdateManyMutationInput!, where: StoredFoodWhereInput): BatchPayload!
  upsertStoredFood(where: StoredFoodWhereUniqueInput!, create: StoredFoodCreateInput!, update: StoredFoodUpdateInput!): StoredFood!
  deleteStoredFood(where: StoredFoodWhereUniqueInput!): StoredFood
  deleteManyStoredFoods(where: StoredFoodWhereInput): BatchPayload!
  createValidEstimate(data: ValidEstimateCreateInput!): ValidEstimate!
  updateValidEstimate(data: ValidEstimateUpdateInput!, where: ValidEstimateWhereUniqueInput!): ValidEstimate
  updateManyValidEstimates(data: ValidEstimateUpdateManyMutationInput!, where: ValidEstimateWhereInput): BatchPayload!
  upsertValidEstimate(where: ValidEstimateWhereUniqueInput!, create: ValidEstimateCreateInput!, update: ValidEstimateUpdateInput!): ValidEstimate!
  deleteValidEstimate(where: ValidEstimateWhereUniqueInput!): ValidEstimate
  deleteManyValidEstimates(where: ValidEstimateWhereInput): BatchPayload!
}

enum MutationType {
  CREATED
  UPDATED
  DELETED
}

interface Node {
  id: ID!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  food(where: FoodWhereUniqueInput!): Food
  foods(where: FoodWhereInput, orderBy: FoodOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Food]!
  foodsConnection(where: FoodWhereInput, orderBy: FoodOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): FoodConnection!
  ingredient(where: IngredientWhereUniqueInput!): Ingredient
  ingredients(where: IngredientWhereInput, orderBy: IngredientOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Ingredient]!
  ingredientsConnection(where: IngredientWhereInput, orderBy: IngredientOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): IngredientConnection!
  recipe(where: RecipeWhereUniqueInput!): Recipe
  recipes(where: RecipeWhereInput, orderBy: RecipeOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Recipe]!
  recipesConnection(where: RecipeWhereInput, orderBy: RecipeOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): RecipeConnection!
  space(where: SpaceWhereUniqueInput!): Space
  spaces(where: SpaceWhereInput, orderBy: SpaceOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Space]!
  spacesConnection(where: SpaceWhereInput, orderBy: SpaceOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): SpaceConnection!
  storedFood(where: StoredFoodWhereUniqueInput!): StoredFood
  storedFoods(where: StoredFoodWhereInput, orderBy: StoredFoodOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [StoredFood]!
  storedFoodsConnection(where: StoredFoodWhereInput, orderBy: StoredFoodOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): StoredFoodConnection!
  validEstimate(where: ValidEstimateWhereUniqueInput!): ValidEstimate
  validEstimates(where: ValidEstimateWhereInput, orderBy: ValidEstimateOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [ValidEstimate]!
  validEstimatesConnection(where: ValidEstimateWhereInput, orderBy: ValidEstimateOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): ValidEstimateConnection!
  node(id: ID!): Node
}

type Recipe {
  id: ID!
  name: String!
  ingredients(where: IngredientWhereInput, orderBy: IngredientOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Ingredient!]
  updatedAt: DateTime!
  createdAt: DateTime!
}

type RecipeConnection {
  pageInfo: PageInfo!
  edges: [RecipeEdge]!
  aggregate: AggregateRecipe!
}

input RecipeCreateInput {
  id: ID
  name: String!
  ingredients: IngredientCreateManyInput
}

type RecipeEdge {
  node: Recipe!
  cursor: String!
}

enum RecipeOrderByInput {
  id_ASC
  id_DESC
  name_ASC
  name_DESC
  updatedAt_ASC
  updatedAt_DESC
  createdAt_ASC
  createdAt_DESC
}

type RecipePreviousValues {
  id: ID!
  name: String!
  updatedAt: DateTime!
  createdAt: DateTime!
}

type RecipeSubscriptionPayload {
  mutation: MutationType!
  node: Recipe
  updatedFields: [String!]
  previousValues: RecipePreviousValues
}

input RecipeSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: RecipeWhereInput
  AND: [RecipeSubscriptionWhereInput!]
  OR: [RecipeSubscriptionWhereInput!]
  NOT: [RecipeSubscriptionWhereInput!]
}

input RecipeUpdateInput {
  name: String
  ingredients: IngredientUpdateManyInput
}

input RecipeUpdateManyMutationInput {
  name: String
}

input RecipeWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  name: String
  name_not: String
  name_in: [String!]
  name_not_in: [String!]
  name_lt: String
  name_lte: String
  name_gt: String
  name_gte: String
  name_contains: String
  name_not_contains: String
  name_starts_with: String
  name_not_starts_with: String
  name_ends_with: String
  name_not_ends_with: String
  ingredients_every: IngredientWhereInput
  ingredients_some: IngredientWhereInput
  ingredients_none: IngredientWhereInput
  updatedAt: DateTime
  updatedAt_not: DateTime
  updatedAt_in: [DateTime!]
  updatedAt_not_in: [DateTime!]
  updatedAt_lt: DateTime
  updatedAt_lte: DateTime
  updatedAt_gt: DateTime
  updatedAt_gte: DateTime
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  AND: [RecipeWhereInput!]
  OR: [RecipeWhereInput!]
  NOT: [RecipeWhereInput!]
}

input RecipeWhereUniqueInput {
  id: ID
}

type Space {
  id: ID!
  name: String!
  storeAs: StorageMethod!
  foods(where: StoredFoodWhereInput, orderBy: StoredFoodOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [StoredFood!]
  icon: String
  updatedAt: DateTime!
  createdAt: DateTime!
}

type SpaceConnection {
  pageInfo: PageInfo!
  edges: [SpaceEdge]!
  aggregate: AggregateSpace!
}

input SpaceCreateInput {
  id: ID
  name: String!
  storeAs: StorageMethod!
  foods: StoredFoodCreateManyInput
  icon: String
}

type SpaceEdge {
  node: Space!
  cursor: String!
}

enum SpaceOrderByInput {
  id_ASC
  id_DESC
  name_ASC
  name_DESC
  storeAs_ASC
  storeAs_DESC
  icon_ASC
  icon_DESC
  updatedAt_ASC
  updatedAt_DESC
  createdAt_ASC
  createdAt_DESC
}

type SpacePreviousValues {
  id: ID!
  name: String!
  storeAs: StorageMethod!
  icon: String
  updatedAt: DateTime!
  createdAt: DateTime!
}

type SpaceSubscriptionPayload {
  mutation: MutationType!
  node: Space
  updatedFields: [String!]
  previousValues: SpacePreviousValues
}

input SpaceSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: SpaceWhereInput
  AND: [SpaceSubscriptionWhereInput!]
  OR: [SpaceSubscriptionWhereInput!]
  NOT: [SpaceSubscriptionWhereInput!]
}

input SpaceUpdateInput {
  name: String
  storeAs: StorageMethod
  foods: StoredFoodUpdateManyInput
  icon: String
}

input SpaceUpdateManyMutationInput {
  name: String
  storeAs: StorageMethod
  icon: String
}

input SpaceWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  name: String
  name_not: String
  name_in: [String!]
  name_not_in: [String!]
  name_lt: String
  name_lte: String
  name_gt: String
  name_gte: String
  name_contains: String
  name_not_contains: String
  name_starts_with: String
  name_not_starts_with: String
  name_ends_with: String
  name_not_ends_with: String
  storeAs: StorageMethod
  storeAs_not: StorageMethod
  storeAs_in: [StorageMethod!]
  storeAs_not_in: [StorageMethod!]
  foods_every: StoredFoodWhereInput
  foods_some: StoredFoodWhereInput
  foods_none: StoredFoodWhereInput
  icon: String
  icon_not: String
  icon_in: [String!]
  icon_not_in: [String!]
  icon_lt: String
  icon_lte: String
  icon_gt: String
  icon_gte: String
  icon_contains: String
  icon_not_contains: String
  icon_starts_with: String
  icon_not_starts_with: String
  icon_ends_with: String
  icon_not_ends_with: String
  updatedAt: DateTime
  updatedAt_not: DateTime
  updatedAt_in: [DateTime!]
  updatedAt_not_in: [DateTime!]
  updatedAt_lt: DateTime
  updatedAt_lte: DateTime
  updatedAt_gt: DateTime
  updatedAt_gte: DateTime
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  AND: [SpaceWhereInput!]
  OR: [SpaceWhereInput!]
  NOT: [SpaceWhereInput!]
}

input SpaceWhereUniqueInput {
  id: ID
}

enum StorageMethod {
  FROZEN
  COLD
  NATURAL
}

type StoredFood {
  id: ID!
  food: Food!
  validThru: String!
}

type StoredFoodConnection {
  pageInfo: PageInfo!
  edges: [StoredFoodEdge]!
  aggregate: AggregateStoredFood!
}

input StoredFoodCreateInput {
  id: ID
  food: FoodCreateOneInput!
  validThru: String!
}

input StoredFoodCreateManyInput {
  create: [StoredFoodCreateInput!]
  connect: [StoredFoodWhereUniqueInput!]
}

type StoredFoodEdge {
  node: StoredFood!
  cursor: String!
}

enum StoredFoodOrderByInput {
  id_ASC
  id_DESC
  validThru_ASC
  validThru_DESC
}

type StoredFoodPreviousValues {
  id: ID!
  validThru: String!
}

input StoredFoodScalarWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  validThru: String
  validThru_not: String
  validThru_in: [String!]
  validThru_not_in: [String!]
  validThru_lt: String
  validThru_lte: String
  validThru_gt: String
  validThru_gte: String
  validThru_contains: String
  validThru_not_contains: String
  validThru_starts_with: String
  validThru_not_starts_with: String
  validThru_ends_with: String
  validThru_not_ends_with: String
  AND: [StoredFoodScalarWhereInput!]
  OR: [StoredFoodScalarWhereInput!]
  NOT: [StoredFoodScalarWhereInput!]
}

type StoredFoodSubscriptionPayload {
  mutation: MutationType!
  node: StoredFood
  updatedFields: [String!]
  previousValues: StoredFoodPreviousValues
}

input StoredFoodSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: StoredFoodWhereInput
  AND: [StoredFoodSubscriptionWhereInput!]
  OR: [StoredFoodSubscriptionWhereInput!]
  NOT: [StoredFoodSubscriptionWhereInput!]
}

input StoredFoodUpdateDataInput {
  food: FoodUpdateOneRequiredInput
  validThru: String
}

input StoredFoodUpdateInput {
  food: FoodUpdateOneRequiredInput
  validThru: String
}

input StoredFoodUpdateManyDataInput {
  validThru: String
}

input StoredFoodUpdateManyInput {
  create: [StoredFoodCreateInput!]
  update: [StoredFoodUpdateWithWhereUniqueNestedInput!]
  upsert: [StoredFoodUpsertWithWhereUniqueNestedInput!]
  delete: [StoredFoodWhereUniqueInput!]
  connect: [StoredFoodWhereUniqueInput!]
  set: [StoredFoodWhereUniqueInput!]
  disconnect: [StoredFoodWhereUniqueInput!]
  deleteMany: [StoredFoodScalarWhereInput!]
  updateMany: [StoredFoodUpdateManyWithWhereNestedInput!]
}

input StoredFoodUpdateManyMutationInput {
  validThru: String
}

input StoredFoodUpdateManyWithWhereNestedInput {
  where: StoredFoodScalarWhereInput!
  data: StoredFoodUpdateManyDataInput!
}

input StoredFoodUpdateWithWhereUniqueNestedInput {
  where: StoredFoodWhereUniqueInput!
  data: StoredFoodUpdateDataInput!
}

input StoredFoodUpsertWithWhereUniqueNestedInput {
  where: StoredFoodWhereUniqueInput!
  update: StoredFoodUpdateDataInput!
  create: StoredFoodCreateInput!
}

input StoredFoodWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  food: FoodWhereInput
  validThru: String
  validThru_not: String
  validThru_in: [String!]
  validThru_not_in: [String!]
  validThru_lt: String
  validThru_lte: String
  validThru_gt: String
  validThru_gte: String
  validThru_contains: String
  validThru_not_contains: String
  validThru_starts_with: String
  validThru_not_starts_with: String
  validThru_ends_with: String
  validThru_not_ends_with: String
  AND: [StoredFoodWhereInput!]
  OR: [StoredFoodWhereInput!]
  NOT: [StoredFoodWhereInput!]
}

input StoredFoodWhereUniqueInput {
  id: ID
}

type Subscription {
  food(where: FoodSubscriptionWhereInput): FoodSubscriptionPayload
  ingredient(where: IngredientSubscriptionWhereInput): IngredientSubscriptionPayload
  recipe(where: RecipeSubscriptionWhereInput): RecipeSubscriptionPayload
  space(where: SpaceSubscriptionWhereInput): SpaceSubscriptionPayload
  storedFood(where: StoredFoodSubscriptionWhereInput): StoredFoodSubscriptionPayload
  validEstimate(where: ValidEstimateSubscriptionWhereInput): ValidEstimateSubscriptionPayload
}

type ValidEstimate {
  id: ID!
  method: StorageMethod!
  estimate: Int!
}

type ValidEstimateConnection {
  pageInfo: PageInfo!
  edges: [ValidEstimateEdge]!
  aggregate: AggregateValidEstimate!
}

input ValidEstimateCreateInput {
  id: ID
  method: StorageMethod!
  estimate: Int!
}

input ValidEstimateCreateManyInput {
  create: [ValidEstimateCreateInput!]
  connect: [ValidEstimateWhereUniqueInput!]
}

type ValidEstimateEdge {
  node: ValidEstimate!
  cursor: String!
}

enum ValidEstimateOrderByInput {
  id_ASC
  id_DESC
  method_ASC
  method_DESC
  estimate_ASC
  estimate_DESC
}

type ValidEstimatePreviousValues {
  id: ID!
  method: StorageMethod!
  estimate: Int!
}

input ValidEstimateScalarWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  method: StorageMethod
  method_not: StorageMethod
  method_in: [StorageMethod!]
  method_not_in: [StorageMethod!]
  estimate: Int
  estimate_not: Int
  estimate_in: [Int!]
  estimate_not_in: [Int!]
  estimate_lt: Int
  estimate_lte: Int
  estimate_gt: Int
  estimate_gte: Int
  AND: [ValidEstimateScalarWhereInput!]
  OR: [ValidEstimateScalarWhereInput!]
  NOT: [ValidEstimateScalarWhereInput!]
}

type ValidEstimateSubscriptionPayload {
  mutation: MutationType!
  node: ValidEstimate
  updatedFields: [String!]
  previousValues: ValidEstimatePreviousValues
}

input ValidEstimateSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: ValidEstimateWhereInput
  AND: [ValidEstimateSubscriptionWhereInput!]
  OR: [ValidEstimateSubscriptionWhereInput!]
  NOT: [ValidEstimateSubscriptionWhereInput!]
}

input ValidEstimateUpdateDataInput {
  method: StorageMethod
  estimate: Int
}

input ValidEstimateUpdateInput {
  method: StorageMethod
  estimate: Int
}

input ValidEstimateUpdateManyDataInput {
  method: StorageMethod
  estimate: Int
}

input ValidEstimateUpdateManyInput {
  create: [ValidEstimateCreateInput!]
  update: [ValidEstimateUpdateWithWhereUniqueNestedInput!]
  upsert: [ValidEstimateUpsertWithWhereUniqueNestedInput!]
  delete: [ValidEstimateWhereUniqueInput!]
  connect: [ValidEstimateWhereUniqueInput!]
  set: [ValidEstimateWhereUniqueInput!]
  disconnect: [ValidEstimateWhereUniqueInput!]
  deleteMany: [ValidEstimateScalarWhereInput!]
  updateMany: [ValidEstimateUpdateManyWithWhereNestedInput!]
}

input ValidEstimateUpdateManyMutationInput {
  method: StorageMethod
  estimate: Int
}

input ValidEstimateUpdateManyWithWhereNestedInput {
  where: ValidEstimateScalarWhereInput!
  data: ValidEstimateUpdateManyDataInput!
}

input ValidEstimateUpdateWithWhereUniqueNestedInput {
  where: ValidEstimateWhereUniqueInput!
  data: ValidEstimateUpdateDataInput!
}

input ValidEstimateUpsertWithWhereUniqueNestedInput {
  where: ValidEstimateWhereUniqueInput!
  update: ValidEstimateUpdateDataInput!
  create: ValidEstimateCreateInput!
}

input ValidEstimateWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  method: StorageMethod
  method_not: StorageMethod
  method_in: [StorageMethod!]
  method_not_in: [StorageMethod!]
  estimate: Int
  estimate_not: Int
  estimate_in: [Int!]
  estimate_not_in: [Int!]
  estimate_lt: Int
  estimate_lte: Int
  estimate_gt: Int
  estimate_gte: Int
  AND: [ValidEstimateWhereInput!]
  OR: [ValidEstimateWhereInput!]
  NOT: [ValidEstimateWhereInput!]
}

input ValidEstimateWhereUniqueInput {
  id: ID
}
`
      }
    